In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


1.


In [ ]:
set1 = {"aman", "222", 777, 400.4}
tup = tuple(set1)
print(tup)

(400.4, 777, 'aman', '222')


2.

In [2]:
dict1 = {"Roll Number": "CB.EN.U4CSE20260","Last Name": "Bhaskaran","First Name": "Siddhartha ","DOB": "06-11-2002"}
print(dict1.keys())
print(dict1.values())
print(dict1)


dict_keys(['Roll Number', 'Last Name', 'First Name', 'DOB'])
dict_values(['CB.EN.U4CSE20260', 'Bhaskaran', 'Siddhartha ', '06-11-2002'])
{'Roll Number': 'CB.EN.U4CSE20260', 'Last Name': 'Bhaskaran', 'First Name': 'Siddhartha ', 'DOB': '06-11-2002'}


3.

In [3]:
import numpy as np
from numpy import random
arr = random.randint(0,1,size = (2,2))
print(arr)

[[0 0]
 [0 0]]


4.

In [ ]:
abs(-1234)

1234

In [5]:
import random
print(random.random())

0.1890081602530823


5.

In [ ]:

print(random.randint(20,90))

49


6.

In [ ]:
set1 = set([11,12,13,14,15])
set2 = random.choices(list(set1), k=3)
print(set2)

[11, 14, 15]


7.

In [6]:
import random
Set1 = set([11, 12, 13, 14, 15])
List = random.choices(list(Set1), k = 3)
print(List)
set2 = random.choice(list(Set1))
print(set2)

[13, 12, 13]
13


8.

In [ ]:
import os
os.getcwd()
os.chdir(r"/content/sample_data")
os.mkdir('document1')
os.chdir('document1')
f = open('document_1.txt','w+')
f.write('The King is Dead, Long Live The King')
f.seek(0)
print(f.read())
f.close()

The King is Dead, Long Live The King


9.

In [ ]:
string = 'The King is Dead, Long Live The King'
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
str = string.split()
print(str)

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


10.

In [7]:
import numpy as np
l=[10,67,89,35]
arr=np.array(l)
print("The first and second elements are",arr[0:2])  

The first and second elements are [10 67]


11.

In [8]:
arr=np.array([[1.,2.,3.],[4.,5.,6.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


12.

In [9]:
print("Second Row",arr[1:][:])
print("Second Col",arr[1:,1])
print("Length of the array :",len(arr))

Second Row [[4. 5. 6.]]
Second Col [5.]
Length of the array : 2


13.

In [10]:
list3=[]
for i in range(10):
  list3.append(np.random.randint(0,100))
oned=np.array(list3)
print("1D array :",oned)
twod=oned.reshape(5,2)
print("2D array :\n",twod)
print("Transpose :\n",twod.T)

1D array : [62 87 62 74  9 93 15 59 10 89]
2D array :
 [[62 87]
 [62 74]
 [ 9 93]
 [15 59]
 [10 89]]
Transpose :
 [[62 62  9 15 10]
 [87 74 93 59 89]]


14.

In [13]:
l=[1,2,3]
newarr=np.array([l])
print(newarr)

[[1 2 3]]


15.

In [ ]:
arr=np.array([1,2,3])
for i in range(len(arr)):
  arr[i]=9
print(arr)

[9 9 9]


16.

In [ ]:
arr=np.array([2,4,5])
sum=0
for i in arr:
  sum+=i
print(sum)

11


17.

In [ ]:
arr=np.array([77,74,75])
prod=1
for i in arr:
  prod*=i
print(prod)

427350


18.

In [ ]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.median(arr))
print(np.argmax(arr))
print(np.std(arr))

12.461538461538462
367.32544378698225
56
1
1
2.0
12
19.165736192147232


19.

In [12]:
arr=np.array([1, 1, 7, 5, 5, 5, 4])
temp=np.array(np.unique(arr))
temp.sort()
print(temp)

[1 4 5 7]


20.

In [ ]:
x=np.array([1,2,3])
y=np.array([0,1,1])
print(np.dot(x,y))

5


21.

In [11]:
import numpy as np
from numpy.linalg import eig
a = np.array([[6, -8], 
              [1, -5]])
w,v=eig(a)
print(w)
print(v)

[ 5.21699057 -4.21699057]
[[0.99524427 0.61650392]
 [0.09741071 0.78735184]]
